-- SQL para criar a tabela de leads no Supabase
-- Copie e cole isso no SQL Editor do seu projeto Supabase

CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    interesse TEXT,
    origem TEXT, -- 'ICP' ou 'Seminar'
    status TEXT DEFAULT 'Lead', -- 'Lead', 'No Checkout', 'Pago', 'Abandonado'
    suggested_remarketing TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ativar RLS (Opcional, mas recomendado para segurança)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir inserção anônima (se for usar via cliente JS direta)
-- Como estamos usando Service Role no Backend Python, o Python passa por cima das políticas.
CREATE POLICY "Allow Service Role Access" ON leads
FOR ALL
USING (true)
WITH CHECK (true);
